name: Test arch4edu on ARM

on:
  push:
    branches: [main]

jobs:
  push_image:
    runs-on: ARM64
    container:
      image: arch4edu/archlinuxarm
      options: --privileged
      volumes:
        - /build:/mnt
        - /build:/var/cache/pacman

    steps:
      - name: Install runtime dependencies
        run: |
          mkdir -p /mnt/sync /var/lib/pacman
          rm -rf /var/lib/pacman/sync
          ln -sf /mnt/sync /var/lib/pacman/sync
          sed '/\[community\]/,+2d' -i /etc/pacman.conf || :
          echo 'Server = https://archlinuxarm.arch4edu.org/$arch/$repo' > /etc/pacman.d/mirrorlist
          pacman-key --init
          pacman-key --populate archlinuxarm
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed --assume-installed python-dulwich base-devel devtools-alarm dbus git github-cli jq pacman-contrib pyalpm python-mysqlclient wget yq zsh
          sed '/\[community\]/,+2d' -i /usr/share/devtools/pacman*.conf || :
