name: Test Rust bindings for preCICE unstable

on:
  push:
    branches: [main]
    paths:
      - docker/actions-git.Dockerfile
  schedule:
    - cron: "0 2 * * 5"

jobs:
  test_bindings:
    runs-on: ubuntu-22.04
    container: ghcr.io/carlosal1015/aur/actions-git:latest
    env:
      URL: "https://github.com/precice/rust-bindings.git"
      PACKAGES: "cargo"
    steps:
      - name: Install Rust bindings for preCICE
        run: |
          pacman --needed --noconfirm --noprogressbar -Syuq ${PACKAGES} >/dev/null 2>&1
          pacman -Qi ${PACKAGES}
          cargo init
          cargo add --git ${URL} precice
          cargo build --release --all-targets

      - name: Run Rust bindings's tests for preCICE
        run: |
          pushd ~/.cargo/registry/src/index.crates.io-*/precice-*
          cargo run --release --example=solverdummy -- examples/precice-config.xml SolverOne &
          cargo run --release --example=solverdummy -- examples/precice-config.xml SolverTwo
          popd
