name: Test Julia bindings for preCICE unstable

on:
  push:
    branches: [main]
    paths:
      - docker/actions-git.Dockerfile
  schedule:
    - cron: "0 2 * * 5"

jobs:
  test_bindings:
    runs-on: ubuntu-22.04
    container: ghcr.io/carlosal1015/aur/actions-git:latest
    env:
      URL: "https://github.com/precice/PreCICE.jl.git"
      PACKAGES: "julia"
      JULIA_NUM_THREADS: "$(nproc)"
    steps:
      - name: Install Julialang bindings for preCICE
        run: |
          pacman --needed --noconfirm --noprogressbar -Syuq ${PACKAGES} >/dev/null 2>&1
          pacman -Qi ${PACKAGES}
          julia -e 'import Pkg; Pkg.add(url=ENV["URL"]); using PreCICE;'

      - name: Run Julialang bindings's tests for preCICE
        run: |
          pushd ~/.julia/packages/PreCICE/*/test
          make && julia runtests.jl
          popd
