name: Test Rust bindings for preCICE stable

on:
  push:
    branches: [main]
    paths:
      - docker/actions.Dockerfile
  schedule:
    - cron: "0 2 * * 5"

jobs:
  test_bindings:
    runs-on: ubuntu-24.04
    container: ghcr.io/carlosal1015/aur/actions:latest
    env:
      PACKAGES: "cargo"
      VERSION: "3.2.0"
      CARGOFLAG: "--release"
    steps:
      - name: Install Rust bindings for preCICE
        run: |
          pacman --needed --noconfirm --noprogressbar -Syuq ${PACKAGES} #>/dev/null 2>&1
          pacman -Qi ${PACKAGES} precice
          cargo init
          cargo add precice@${VERSION::3}
          cargo build ${CARGOFLAG} --all-targets

      - name: Run Rust bindings's tests for preCICE
        run: |
          pushd ~/.cargo/registry/src/index.crates.io-*/precice-${VERSION}/examples
          cargo run ${CARGOFLAG} --example=solverdummy -- precice-config.xml SolverOne &
          cargo run ${CARGOFLAG} --example=solverdummy -- precice-config.xml SolverTwo
          popd
