name: Test Rust bindings for preCICE unstable

on:
  push:
    branches: [main]
    paths:
      - docker/actions-git.Dockerfile
  schedule:
    - cron: "0 2 1 * *"

jobs:
  test_bindings:
    runs-on: ubuntu-24.04
    container: ghcr.io/carlosal1015/aur/actions-git:latest
    env:
      URL: "https://github.com/precice/rust-bindings.git"
      PACKAGES: "cargo"
      # TODO: Maybe libbacktrace-git is a dependency, e.g. try this incorrect execution
      # cargo run ${CARGOFLAG} --example=solverdummy -- examples/precice-config.xml SolverOne &
      CARGOFLAG: "--release"
    steps:
      - name: Install Rust bindings for preCICE
        run: |
          # curl -s https://gitlab.com/dune-archiso/dune-archiso.gitlab.io/-/raw/main/templates/add_archlinuxcn.sh | bash
          pacman --needed --noconfirm --noprogressbar -Syuq ${PACKAGES} #>/dev/null 2>&1
          pacman -Qi ${PACKAGES} precice-git
          cargo init
          cargo add --git ${URL} precice
          cargo build ${CARGOFLAG} --all-targets

      - name: Run Rust bindings's tests for preCICE
        run: |
          pushd ~/.cargo/git/checkouts/rust-bindings-*/*/examples/
          cargo run ${CARGOFLAG} --example=solverdummy -- precice-config.xml SolverOne &
          cargo run ${CARGOFLAG} --example=solverdummy -- precice-config.xml SolverTwo
          popd
