name: pypreCICE docs

on:
  push:
    branches: [main]
    paths:
      - docker/actions.Dockerfile

jobs:
  build_sphinx_4:
    runs-on: ubuntu-22.04
    container: ghcr.io/carlosal1015/aur/actions:latest
    env:
      URL: "https://github.com/precice/python-bindings"
      TAG: "v2.5.0.0"
    steps:
      - name: Build html
        run: |
          git config --global advice.detachedHead false
          pacman --needed --noconfirm --noprogressbar -Syyuq
          pacman -S --noconfirm python-pip
          python -m venv --system-site-packages ~/sphinx-env
          source ~/sphinx-env/bin/activate
          pip install sphinx==4.5.0
          git clone -q --filter=blob:none --depth=1 --branch $TAG $URL.git
          pushd python-bindings
          printf "y\npypreCICE\npreCICE community\n$TAG\nen\n" | sphinx-quickstart
          sed -i '/import os/,+3 s/^# //' source/conf.py
          sed -i '/extensions =/a \ \ "sphinx.ext.autodoc"' source/conf.py
          sed -i 's/alabaster/furo/' source/conf.py
          python setup.py build_ext --inplace
          sphinx-apidoc -o source .
          make html
          popd

      # build_sphinx_5:
      #     runs-on: ubuntu-22.04
      #     container: ghcr.io/carlosal1015/aur/actions:latest
      #     env:
      #       URL: "https://github.com/precice/python-bindings"
      #       TAG: "v2.5.0.0"
      #     steps:
      #       - name: Build html
      #         run: |
      #           git config --global advice.detachedHead false
      #           git clone -q --filter=blob:none --depth=1 --branch $TAG $URL.git
      #           pushd python-bindings
      #           printf "y\npypreCICE\npreCICE community\n$TAG\nen\n" | sphinx-quickstart
      #           sed -i '8 a import os' source/conf.py
      #           sed -i '9 a import sys' source/conf.py
      #           sed -i "10 a sys.path.insert(0, os.path.abspath('.'))" source/conf.py
      #           sed -i 's/extensions = \[\]/extensions = \["sphinx.ext.autodoc"\]/' source/conf.py
      #           sed -i 's/alabaster/furo/' source/conf.py
      #           python setup.py build_ext --inplace
      #           sphinx-apidoc -o source .
      #           make html
      #           popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: python-bindings/build/html
          force_orphan: true
          publish_branch: gh-pages
