name: pypreCICE docs

on:
  push:
    branches: [main]
    paths:
      - docker/actions.Dockerfile

jobs:
  build_sphinx:
    runs-on: ubuntu-22.04
    container: ghcr.io/carlosal1015/aur/actions:latest
    env:
      URL: "https://github.com/precice/python-bindings"
      TAG: "v3.0.0.0"
      PACKAGES: "cython git python-pkgconfig python-setuptools python-sphinx-furo"
    steps:
      - name: Build html
        run: |
          pacman --needed --noconfirm --noprogressbar -Syuq ${PACKAGES} >/dev/null 2>&1
          git config --global advice.detachedHead false
          git clone -q --filter=blob:none --depth=1 --branch $TAG $URL.git
          pushd python-bindings
          printf "y\npypreCICE\npreCICE community\n$TAG\nen\n" | sphinx-quickstart
          sed -i 's/extensions = \[\]/extensions = \["sphinx.ext.autodoc"\]/' source/conf.py
          sed -i 's/alabaster/furo/' source/conf.py
          python setup.py build_ext --inplace
          export _pyversion=$(python -c "import sys; print(f'{sys.version_info.major}{sys.version_info.minor}')")
          export CARCH=$(uname -m)
          sphinx-apidoc -o source . # ./*setup* ./*test*
          PYTHONPATH="${PWD}/build/lib.linux-${CARCH}-cpython-${_pyversion}:${PYTHONPATH}" make html
          popd
          # sed -i '/import os/,+3 s/^# //' source/conf.py
          # sed -i '8 a import os' source/conf.py
          # sed -i '9 a import sys' source/conf.py
          # sed -i "10 a sys.path.insert(0, os.path.abspath('.'))" source/conf.py
          # sed -i '/extensions =/a \ \ "sphinx.ext.autodoc"' source/conf.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: python-bindings/build/html
          force_orphan: true
          publish_branch: gh-pages
