name: pypreCICE docs

on:
  push:
    branches: [main]
    paths:
      - docker/actions.Dockerfile

jobs:
  build_sphinx:
    runs-on: ubuntu-22.04
    container: ghcr.io/carlosal1015/aur/actions:latest
    env:
      URL: "https://github.com/precice/python-bindings"
      TAG: "v2.5.0.0"
    steps:
      - name: Build html
        run: |
          git clone -q --filter=blob:none --depth=1 --branch $TAG $URL.git
          pushd python-bindings
          printf "y\npypreCICE\npreCICE community\n$TAG\nen\n" | sphinx-quickstart
          sed -i '/import os/,+3 s/^# //' source/conf.py
          sed -i '/extensions =/a \ \ "sphinx.ext.autodoc"' source/conf.py
          sed -i 's/alabaster/furo/' source/conf.py
          python setup.py build_ext --inplace
          sphinx-apidoc -o source .
          make html
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: python-bindings/build/html
