name: deal.II test over Arch

on:
  push:
    branches: [main]
    paths:
      - docker/test-deal-ii.Dockerfile

jobs:
  tests:
    runs-on: ubuntu-22.04
    container: ghcr.io/carlosal1015/aur/test-deal-ii:latest
    env:
      URL: "https://github.com/dealii/dealii"
      TAG: "v9.3.3"
    steps:
      - name: Clone latest stable deal.II code
        run: |
          git config --global advice.detachedHead false
          git clone -q --filter=blob:none --depth=1 --branch $TAG $URL.git

      - name: Build and list the tests
        run: |
          cmake -S dealii/tests -B tests_for_installed_dealii -DDEAL_II_DIR=/usr -Wno-dev
          cmake --build tests_for_installed_dealii --target setup_tests
          ctest -N --test-dir tests_for_installed_dealii

      - name: Run 8130 tests
        run: |
          run.sh -p test
