name: deal.II test over Arch

on:
  push:
    branches: [main]
    paths:
      - docker/test-deal-ii.Dockerfile

jobs:
  tests:
    runs-on: ubuntu-25.04
    container: ghcr.io/carlosal1015/aur/test-deal-ii:latest
    env:
      URL: "https://github.com/dealii/dealii"
      TAG: "v9.6.0"
    steps:
      - name: Copy the examples from latest stable deal.II code
        run: |
          git config --global advice.detachedHead false
          git clone -q --filter=blob:none --depth=1 --branch $TAG $URL.git
          # mkdir -p dealii/examples
          # cp -R /usr/share/deal-ii/examples/* dealii/examples

      - name: Run 79 examples
        run: |
          run.sh -p example
