name: Test Julia language bindings for preCICE unstable

on:
  push:
    branches: [main]
    paths:
      - docker/*.Dockerfile
  schedule:
    - cron: "0 2 * * 5"

jobs:
  test_bindings:
    runs-on: ubuntu-22.04
    container: archlinux:base-devel
    env:
      URL: "https://github.com/precice/PreCICE.jl.git"
      PACKAGES: "openssh precice-git julia"
      JULIA_NUM_THREADS: "$(nproc)"
      GPG_KEY: "8C43C00BA8F06ECA"
    steps:
      - name: Add Third-Party repository
        run: |
          ln -s /usr/share/zoneinfo/America/Lima /etc/localtime
          sed -i 's/^#Color/Color/' /etc/pacman.conf
          sed -i '/#CheckSpace/a ILoveCandy' /etc/pacman.conf
          sed -i 's/^ParallelDownloads = 5/ParallelDownloads = 30/' /etc/pacman.conf
          sed -i 's/^VerbosePkgLists/#VerbosePkgLists/' /etc/pacman.conf
          sed -i 's/^#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc)"/' /etc/makepkg.conf
          pacman-key --init
          pacman-key --populate archlinux
          pacman-key --recv-keys ${GPG_KEY}
          pacman-key --finger ${GPG_KEY}
          pacman-key --lsign-key ${GPG_KEY}
          echo -e '\n[dune-archiso-repository-core]\nSigLevel = Required DatabaseOptional\nServer = https://dune-archiso.gitlab.io/repository/dune-archiso-repository-core/$arch\n[precice-arch]\nSigLevel = Required DatabaseOptional\nServer = https://dune-archiso.gitlab.io/testing/precice-arch/$arch\n' | tee -a /etc/pacman.conf

      - name: Install Julialang bindings for preCICE
        run: |
          pacman --needed --noconfirm --noprogressbar -Syyuq ${PACKAGES} >/dev/null 2>&1
          pacman -Qi ${PACKAGES}
          julia -e 'import Pkg; Pkg.add(url=ENV["URL"]); using PreCICE;'

      - name: Run Julialang bindings's tests for preCICE
        run: |
          pushd ~/.julia/packages/PreCICE/*/test
          if [ -z "$(ldconfig -p | grep libcuda.so.1)" ]; then export OMPI_MCA_opal_warn_on_missing_libcuda=0 ; fi
          make && julia runtests.jl
          popd
